name: ESLintãƒã‚§ãƒƒã‚¯
on: push

jobs:
  eslint:
    name: ESLintãƒã‚§ãƒƒã‚¯
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Yarnã‚­ãƒ£ãƒƒã‚·ãƒ¥ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªãƒ‘ã‚¹å–å¾—
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn run lintjs:fix --max-warnings 0
      - name: è‡ªå‹•ä¿®æ­£ãŒè¡Œã‚ã‚ŒãŸã‹ã‚’å–å¾—
        id: diff
        run: |
          echo "::set-output name=fixed::$(if (git diff --shortstat | grep '[0-9]'); then echo yes; fi)"
      - run: echo $LOG
        env:
          LOG: ${{ steps.diff.outputs.fixed }}
      - if: steps.diff.outputs.fixed == 'yes'
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .;
          git commit -m "ğŸ‘• Fixed auto-fixable ESLint errors by github-actions";
          git push origin HEAD:${GITHUB_REF};
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
